version: 2

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/source/conf.py

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.14"
  jobs:
    build:
      html:
        - NOCOLOR=1 sphinx-build -T -b html docs/source $READTHEDOCS_OUTPUT/html

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

formats: []
